exports.productsInformations = 'Products Informations';
exports.products = [
  {
    productName: 'sebzeler',
    description: ['Marul', 'patates', 'soğan'],
    explanation: 'Bu elma antalyada yetişti ve organiktir. Sulu ve ekşidir.',
    src: [
      '../../img/sebzeler/domates.jpg',
      '../../img/sebzeler/ceri_salkim_domates.jpg',
      '../../img/sebzeler/ciko_domates.jpg',
      '../../img/sebzeler/kokteyl_seyit_domates.jpg',
      '../../img/sebzeler/pembe_domates.jpg',
      '../../img/sebzeler/pembe_kokteyl_domates.jpg',
      '../../img/sebzeler/salkim_domates.jpg',
      '../../img/sebzeler/sari_kokteyl_domates.jpg',
      '../../img/sebzeler/zebra_domates.jpg',
      '../../img/sebzeler/sili_biber.jpg',
      '../../img/sebzeler/sivri_biber.jpg',
      '../../img/sebzeler/dolmalik_biber.jpg',
      '../../img/sebzeler/kalifornia_biber.jpg',
      '../../img/sebzeler/kapya_biber.jpg',
      '../../img/sebzeler/macar_dolmalik_biber.jpg',
      '../../img/sebzeler/macar_sivri_biber.jpg',
      '../../img/sebzeler/patlican.jpg',
      '../../img/sebzeler/topak_patlican.jpg',
      '../../img/sebzeler/brokoli.jpg',
      '../../img/sebzeler/carliston_biber.jpg',
      '../../img/sebzeler/dikenli_hiyar.jpg',
      '../../img/sebzeler/havuc.jpg',
      '../../img/sebzeler/hiyar.jpg',
      '../../img/sebzeler/kabak.jpg',
      '../../img/sebzeler/karnibahar.jpg',
      '../../img/sebzeler/lahana.jpg',
    ],
    names: [
      'Domates',
      'Çeri Salkım Domates',
      'Çiko Domates',
      'Kokteyl Şeyit Domates',
      'Pembe Domates',
      'Pembe Kokteyl Domates',
      'Salkım Domates',
      'Sarı Kokteyl Domates',
      'Zebra Domates',
      'Sili Biber',
      'Sivri Biber',
      'Dolmalık Biber',
      'Kaliforniya Biber',
      'Kapya Biber',
      'Macar Dolmalık Biber',
      'Macar Sivri Biber',
      'Patlıcan',
      'Topak Patlıcan',
      'Brokoli',
      'Carliston Biber',
      'Dikenli Hiyar',
      'Havuç',
      'Hiyar',
      'Kabak',
      'Karnabahar',
      'Lahana',
    ],
  },
  {
    productName: 'meyveler',
    description: ['elma', 'armut', 'çilek'],
    explanation: 'Bu kiraz antalyada yetişti ve organiktir. Sulu ve ekşidir.',
    src: [
      '../../img/meyveler/armut.jpg',
      '../../img/meyveler/ayva.jpg',
      '../../img/meyveler/greyfurt.jpg',
      '../../img/meyveler/incir.jpg',
      '../../img/meyveler/karpuz.jpg',
      '../../img/meyveler/kavun.jpg',
      '../../img/meyveler/kayisi.jpg',
      '../../img/meyveler/limon.jpg',
      '../../img/meyveler/mandarin.jpg',
      '../../img/meyveler/nar.jpg',
      '../../img/meyveler/nektarin.jpg',
      '../../img/meyveler/seftali.jpg',
      '../../img/meyveler/portakal.jpg',
      '../../img/meyveler/uzum.jpg',
      '../../img/meyveler/siyah_erik.jpg',
      '../../img/meyveler/yesil_erik.jpg',
    ],
    names: [
      'Armut',
      'Ayva',
      'Greyfurt',
      'İncir',
      'Karpuz',
      'Kavun',
      'Kayısı',
      'Limon',
      'Mandarin',
      'Nar',
      'Nektari',
      'Şeftali',
      'Portakal',
      'Üzüm',
      'Siyah Erik',
      'Yeşil Erik',
    ],
  },
  {
    productName: 'seralar',
    description: [
      'Fide Seraları',
      'Topraksız Tarım Seraları',
      'Hidroponik Seralar',
    ],
    explanation: 'Bu kiraz antalyada yetişti ve organiktir. Sulu ve ekşidir.',
    src: [
      '../../img/1-fideTesisi1.jpg',
      '../../img/2-topraksızTarım1.jpg',
      '../../img/3-hidroponikSera1.jpg',
    ],
    names: ['Fide Seraları', 'Topraksız Tarım Seraları', 'Hidroponik Seralar'],
  },
];
